name: build

on: [push, pull_request]

jobs:
  build-with-pip:
    name: ubuntu-latest-3.7
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display versions
        run: python -V; pip -V
      - name: Install depedencies and package
        shell: bash
        run: pip install -U -e .'[tests]'
      - name: Run tests
        run: pytest --cov=framol --pyargs framol
      - name: Generate line coverage
        run: coverage report --show-missing


